import mongoose from "mongoose";
import { connectDB } from "../config/db.js";
import { Product } from "../models/product.model.js";

const products = [
  {
    name: "Royal Bengal Handloom Cotton Saree",
    description:
      "Authentic Santipur handloom cotton saree woven by master weavers using traditional tant technique. Features intricate white jamdani motifs on rich royal blue base. Lightweight, breathable, and perfect for daily wear or office.",
    price: 2499,
    originalPrice: 2999,
    images: [
      "https://picsum.photos/seed/sar-001-1/1000/1300",
      "https://picsum.photos/seed/sar-001-2/1000/1300",
      "https://picsum.photos/seed/sar-001-3/1000/1300",
    ],
    category: "saree",
    subcategory: "tant",
    fabric: "Cotton",
    color: "Royal Blue",
    size: ["Free"],
    stock: 16,
    sku: "SAR-001",
    tags: ["tant", "handloom", "saree", "cotton"],
    isActive: true,
    isFeatured: true,
    rating: 4.2,
    reviewCount: 106,
  },
  {
    name: "Dhakai Jamdani Silk Saree - Royal Blue",
    description:
      "Exquisite Dhakai Jamdani silk saree with real zari work. Each motif takes weeks to weave using the supplementary weft technique passed down generations.",
    price: 8999,
    originalPrice: 10999,
    images: [
      "https://picsum.photos/seed/sar-002-1/1000/1300",
      "https://picsum.photos/seed/sar-002-2/1000/1300",
      "https://picsum.photos/seed/sar-002-3/1000/1300",
    ],
    category: "saree",
    subcategory: "jamdani",
    fabric: "Silk",
    color: "Royal Blue",
    size: ["Free"],
    stock: 48,
    sku: "SAR-002",
    tags: ["jamdani", "handloom", "saree", "silk"],
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 103,
  },
  {
    name: "Santipur Tant Saree - White Gold Border",
    description:
      "Classic Santipur tant cotton saree in pristine white with shimmering gold zari border and pallu. Feather-light drape perfect for Bengal's humidity.",
    price: 3299,
    originalPrice: null,
    images: [
      "https://picsum.photos/seed/sar-003-1/1000/1300",
      "https://picsum.photos/seed/sar-003-2/1000/1300",
      "https://picsum.photos/seed/sar-003-3/1000/1300",
    ],
    category: "saree",
    subcategory: "tant",
    fabric: "Cotton",
    color: "White with Gold Border",
    size: ["Free"],
    stock: 43,
    sku: "SAR-003",
    tags: ["tant", "handloom", "saree", "cotton"],
    isActive: true,
    isFeatured: true,
    rating: 4.3,
    reviewCount: 73,
  },
  {
    name: "Handloom Linen Saree - Indigo Dream",
    description:
      "Premium handloom linen saree in deep indigo with subtle white geometric patterns. Gets softer with each wash.",
    price: 4199,
    originalPrice: 4999,
    images: [
      "https://picsum.photos/seed/sar-004-1/1000/1300",
      "https://picsum.photos/seed/sar-004-2/1000/1300",
      "https://picsum.photos/seed/sar-004-3/1000/1300",
    ],
    category: "saree",
    subcategory: "linen",
    fabric: "Linen",
    color: "Indigo",
    size: ["Free"],
    stock: 49,
    sku: "SAR-004",
    tags: ["linen", "handloom", "saree", "linen"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 48,
  },
  {
    name: "Banarasi Tissue Silk Saree - Champagne Gold",
    description:
      "Luxurious Banarasi tissue silk saree in champagne gold with all-over floral jaal pattern in silver zari.",
    price: 12999,
    originalPrice: 15999,
    images: [
      "https://picsum.photos/seed/sar-005-1/1000/1300",
      "https://picsum.photos/seed/sar-005-2/1000/1300",
      "https://picsum.photos/seed/sar-005-3/1000/1300",
    ],
    category: "saree",
    subcategory: "banarasi",
    fabric: "Silk",
    color: "Champagne Gold",
    size: ["Free"],
    stock: 14,
    sku: "SAR-005",
    tags: ["banarasi", "handloom", "saree", "silk"],
    isActive: true,
    isFeatured: true,
    rating: 4.4,
    reviewCount: 86,
  },
  {
    name: "Muslin Jamdani Saree - Pastel Pink",
    description:
      "Ultra-fine muslin jamdani saree in delicate pastel pink with white floral butis scattered like spring blossoms.",
    price: 6499,
    originalPrice: 7999,
    images: [
      "https://picsum.photos/seed/sar-006-1/1000/1300",
      "https://picsum.photos/seed/sar-006-2/1000/1300",
      "https://picsum.photos/seed/sar-006-3/1000/1300",
    ],
    category: "saree",
    subcategory: "muslin",
    fabric: "Muslin",
    color: "Pastel Pink",
    size: ["Free"],
    stock: 22,
    sku: "SAR-006",
    tags: ["muslin", "handloom", "saree", "muslin"],
    isActive: true,
    isFeatured: true,
    rating: 4.5,
    reviewCount: 35,
  },
  {
    name: "Korial Silk Saree - Deep Maroon",
    description:
      "Traditional Bengal Korial silk saree in deep maroon with contrast temple border, ideal for pujas and festive occasions.",
    price: 5499,
    originalPrice: 6299,
    images: [
      "https://picsum.photos/seed/sar-007-1/1000/1300",
      "https://picsum.photos/seed/sar-007-2/1000/1300",
      "https://picsum.photos/seed/sar-007-3/1000/1300",
    ],
    category: "saree",
    subcategory: "korial",
    fabric: "Silk",
    color: "Maroon",
    size: ["Free"],
    stock: 27,
    sku: "SAR-007",
    tags: ["korial", "handloom", "saree", "silk"],
    isActive: true,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 83,
  },
  {
    name: "Baluchari Silk Saree - Mythological Motifs",
    description:
      "Handwoven Baluchari silk saree depicting mythological scenes on the pallu, woven in rich chestnut brown and gold.",
    price: 14999,
    originalPrice: 17999,
    images: [
      "https://picsum.photos/seed/sar-008-1/1000/1300",
      "https://picsum.photos/seed/sar-008-2/1000/1300",
      "https://picsum.photos/seed/sar-008-3/1000/1300",
    ],
    category: "saree",
    subcategory: "baluchari",
    fabric: "Silk",
    color: "Chestnut Brown",
    size: ["Free"],
    stock: 28,
    sku: "SAR-008",
    tags: ["baluchari", "handloom", "saree", "silk"],
    isActive: true,
    isFeatured: true,
    rating: 4.4,
    reviewCount: 95,
  },
  {
    name: "Kantha Stitch Cotton Saree - Ivory",
    description:
      "Hand-embroidered Kantha stitch cotton saree in ivory, featuring running stitch motifs of birds and florals by rural artisans.",
    price: 3799,
    originalPrice: 4499,
    images: [
      "https://picsum.photos/seed/sar-009-1/1000/1300",
      "https://picsum.photos/seed/sar-009-2/1000/1300",
      "https://picsum.photos/seed/sar-009-3/1000/1300",
    ],
    category: "saree",
    subcategory: "kantha",
    fabric: "Cotton",
    color: "Ivory",
    size: ["Free"],
    stock: 32,
    sku: "SAR-009",
    tags: ["kantha", "handloom", "saree", "cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 91,
  },
  {
    name: "Tussar Silk Saree - Natural Beige",
    description:
      "Handloom Tussar silk saree in natural beige with hand-painted Madhubani border, a fusion of Bengal weave and Bihar art.",
    price: 7299,
    originalPrice: 8499,
    images: [
      "https://picsum.photos/seed/sar-010-1/1000/1300",
      "https://picsum.photos/seed/sar-010-2/1000/1300",
      "https://picsum.photos/seed/sar-010-3/1000/1300",
    ],
    category: "saree",
    subcategory: "tussar",
    fabric: "Tussar Silk",
    color: "Beige",
    size: ["Free"],
    stock: 43,
    sku: "SAR-010",
    tags: ["tussar", "handloom", "saree", "tussar-silk"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 113,
  },
  {
    name: "Cotton Silk Saree - Rani Pink",
    description:
      "Soft cotton-silk blend saree in vibrant rani pink with woven paisley border, great for daily festive wear.",
    price: 2899,
    originalPrice: 3399,
    images: [
      "https://picsum.photos/seed/sar-011-1/1000/1300",
      "https://picsum.photos/seed/sar-011-2/1000/1300",
      "https://picsum.photos/seed/sar-011-3/1000/1300",
    ],
    category: "saree",
    subcategory: "cotton-silk",
    fabric: "Cotton Silk",
    color: "Rani Pink",
    size: ["Free"],
    stock: 31,
    sku: "SAR-011",
    tags: ["cotton-silk", "handloom", "saree", "cotton-silk"],
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 22,
  },
  {
    name: "Handloom Cotton Saree - Sea Green Stripes",
    description:
      "Breathable handloom cotton saree in sea green with fine self-stripes and a contrasting maroon border.",
    price: 1999,
    originalPrice: 2399,
    images: [
      "https://picsum.photos/seed/sar-012-1/1000/1300",
      "https://picsum.photos/seed/sar-012-2/1000/1300",
      "https://picsum.photos/seed/sar-012-3/1000/1300",
    ],
    category: "saree",
    subcategory: "tant",
    fabric: "Cotton",
    color: "Sea Green",
    size: ["Free"],
    stock: 28,
    sku: "SAR-012",
    tags: ["tant", "handloom", "saree", "cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 60,
  },
  {
    name: "Katan Silk Saree - Wine Red",
    description:
      "Pure Katan silk saree in wine red with woven gold booti all over and a rich contrast pallu.",
    price: 9999,
    originalPrice: 11999,
    images: [
      "https://picsum.photos/seed/sar-013-1/1000/1300",
      "https://picsum.photos/seed/sar-013-2/1000/1300",
      "https://picsum.photos/seed/sar-013-3/1000/1300",
    ],
    category: "saree",
    subcategory: "katan",
    fabric: "Silk",
    color: "Wine Red",
    size: ["Free"],
    stock: 45,
    sku: "SAR-013",
    tags: ["katan", "handloom", "saree", "silk"],
    isActive: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 115,
  },
  {
    name: "Handloom Cotton Saree - Sunshine Yellow",
    description:
      "Lightweight handloom cotton saree in sunshine yellow with a thin black border, perfect for everyday elegance.",
    price: 1899,
    originalPrice: 2199,
    images: [
      "https://picsum.photos/seed/sar-014-1/1000/1300",
      "https://picsum.photos/seed/sar-014-2/1000/1300",
      "https://picsum.photos/seed/sar-014-3/1000/1300",
    ],
    category: "saree",
    subcategory: "tant",
    fabric: "Cotton",
    color: "Yellow",
    size: ["Free"],
    stock: 43,
    sku: "SAR-014",
    tags: ["tant", "handloom", "saree", "cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 35,
  },
  {
    name: "Organza Silk Saree - Powder Blue",
    description:
      "Sheer organza silk saree in powder blue with delicate sequin embroidery, ideal for cocktail and reception events.",
    price: 6999,
    originalPrice: 8299,
    images: [
      "https://picsum.photos/seed/sar-015-1/1000/1300",
      "https://picsum.photos/seed/sar-015-2/1000/1300",
      "https://picsum.photos/seed/sar-015-3/1000/1300",
    ],
    category: "saree",
    subcategory: "organza",
    fabric: "Organza Silk",
    color: "Powder Blue",
    size: ["Free"],
    stock: 37,
    sku: "SAR-015",
    tags: ["organza", "handloom", "saree", "organza-silk"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 89,
  },
  {
    name: "Handloom Tant Saree - Charcoal Grey",
    description:
      "Modern charcoal grey tant saree with minimal geometric border, designed for the contemporary saree wearer.",
    price: 2699,
    originalPrice: 3199,
    images: [
      "https://picsum.photos/seed/sar-016-1/1000/1300",
      "https://picsum.photos/seed/sar-016-2/1000/1300",
      "https://picsum.photos/seed/sar-016-3/1000/1300",
    ],
    category: "saree",
    subcategory: "tant",
    fabric: "Cotton",
    color: "Charcoal Grey",
    size: ["Free"],
    stock: 28,
    sku: "SAR-016",
    tags: ["tant", "handloom", "saree", "cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 108,
  },
  {
    name: "Patola Silk Saree - Multicolor Ikat",
    description:
      "Double ikat Patola silk saree with vibrant multicolor geometric patterns, a rare collector's textile.",
    price: 18999,
    originalPrice: 22999,
    images: [
      "https://picsum.photos/seed/sar-017-1/1000/1300",
      "https://picsum.photos/seed/sar-017-2/1000/1300",
      "https://picsum.photos/seed/sar-017-3/1000/1300",
    ],
    category: "saree",
    subcategory: "patola",
    fabric: "Silk",
    color: "Multicolor",
    size: ["Free"],
    stock: 43,
    sku: "SAR-017",
    tags: ["patola", "handloom", "saree", "silk"],
    isActive: true,
    isFeatured: true,
    rating: 4.5,
    reviewCount: 26,
  },
  {
    name: "Chiffon Printed Saree - Floral Pastels",
    description:
      "Lightweight chiffon saree with all-over floral print in pastel tones, easy to drape and carry through the day.",
    price: 1799,
    originalPrice: 2199,
    images: [
      "https://picsum.photos/seed/sar-018-1/1000/1300",
      "https://picsum.photos/seed/sar-018-2/1000/1300",
      "https://picsum.photos/seed/sar-018-3/1000/1300",
    ],
    category: "saree",
    subcategory: "printed",
    fabric: "Chiffon",
    color: "Pastel Multicolor",
    size: ["Free"],
    stock: 45,
    sku: "SAR-018",
    tags: ["printed", "handloom", "saree", "chiffon"],
    isActive: true,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 53,
  },
  {
    name: "Handloom Cotton Saree - Classic Checks",
    description:
      "Everyday handloom cotton saree in classic red and black checks with a simple woven border.",
    price: 1699,
    originalPrice: 1999,
    images: [
      "https://picsum.photos/seed/sar-019-1/1000/1300",
      "https://picsum.photos/seed/sar-019-2/1000/1300",
      "https://picsum.photos/seed/sar-019-3/1000/1300",
    ],
    category: "saree",
    subcategory: "tant",
    fabric: "Cotton",
    color: "Red & Black Checks",
    size: ["Free"],
    stock: 47,
    sku: "SAR-019",
    tags: ["tant", "handloom", "saree", "cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 88,
  },
  {
    name: "Silk Cotton Saree - Turmeric Yellow",
    description:
      "Comfortable silk-cotton blend saree in turmeric yellow with a temple border, suited for pujas and gatherings.",
    price: 3199,
    originalPrice: 3699,
    images: [
      "https://picsum.photos/seed/sar-020-1/1000/1300",
      "https://picsum.photos/seed/sar-020-2/1000/1300",
      "https://picsum.photos/seed/sar-020-3/1000/1300",
    ],
    category: "saree",
    subcategory: "silk-cotton",
    fabric: "Silk Cotton",
    color: "Turmeric Yellow",
    size: ["Free"],
    stock: 36,
    sku: "SAR-020",
    tags: ["silk-cotton", "handloom", "saree", "silk-cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 104,
  },
  {
    name: "Budget Handloom Cotton Saree - Coral Pink",
    description:
      "Everyday handloom cotton saree in coral pink with a simple woven border. Soft, breathable, and great value for daily wear.",
    price: 449,
    originalPrice: 899,
    images: [
      "https://images.unsplash.com/photo-1727430228383-aa1fb59db8bf?auto=format&fit=crop&w=1000&h=1300&q=80",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&h=1300&q=80",
      "https://images.unsplash.com/photo-1610030469839-f909584b43f1?auto=format&fit=crop&w=1000&h=1300&q=80",
    ],
    category: "saree",
    subcategory: "tant",
    fabric: "Cotton",
    color: "Coral Pink",
    size: ["Free"],
    stock: 60,
    sku: "SAR-021",
    tags: ["tant", "budget", "saree", "cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.1,
    reviewCount: 18,
  },
  {
    name: "Budget Printed Cotton Saree - Mustard Floral",
    description:
      "Lightweight printed cotton saree in mustard yellow with an all-over floral pattern. An affordable everyday pick.",
    price: 499,
    originalPrice: 949,
    images: [
      "https://images.unsplash.com/photo-1679006831648-7c9ea12e5807?auto=format&fit=crop&w=1000&h=1300&q=80",
      "https://images.unsplash.com/photo-1609748340041-f5d61e061ebc?auto=format&fit=crop&w=1000&h=1300&q=80",
    ],
    category: "saree",
    subcategory: "printed",
    fabric: "Cotton",
    color: "Mustard Floral",
    size: ["Free"],
    stock: 58,
    sku: "SAR-022",
    tags: ["printed", "budget", "saree", "cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.0,
    reviewCount: 12,
  },
  {
    name: "Budget Handloom Cotton Saree - Sea Blue",
    description:
      "Simple handloom cotton saree in sea blue with a thin contrast border, made for daily comfort at an accessible price.",
    price: 529,
    originalPrice: 999,
    images: [
      "https://images.unsplash.com/photo-1610189012906-4c0aa9b9781e?auto=format&fit=crop&w=1000&h=1300&q=80",
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=1000&h=1300&q=80",
      "https://images.unsplash.com/photo-1678705730064-a7ecbab4b3fb?auto=format&fit=crop&w=1000&h=1300&q=80",
    ],
    category: "saree",
    subcategory: "tant",
    fabric: "Cotton",
    color: "Sea Blue",
    size: ["Free"],
    stock: 65,
    sku: "SAR-023",
    tags: ["tant", "budget", "saree", "cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 24,
  },
  {
    name: "Budget Cotton Silk Saree - Emerald Green",
    description:
      "Everyday cotton-silk blend saree in emerald green with a woven border, priced for daily festive wear.",
    price: 579,
    originalPrice: 899,
    images: [
      "https://images.unsplash.com/flagged/photo-1551854716-8b811be39e7e?auto=format&fit=crop&w=1000&h=1300&q=80",
      "https://images.unsplash.com/photo-1641699862936-be9f49b1c38d?auto=format&fit=crop&w=1000&h=1300&q=80",
    ],
    category: "saree",
    subcategory: "cotton-silk",
    fabric: "Cotton Silk",
    color: "Emerald Green",
    size: ["Free"],
    stock: 52,
    sku: "SAR-024",
    tags: ["cotton-silk", "budget", "saree", "cotton-silk"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 15,
  },
  {
    name: "Budget Handloom Cotton Saree - Off White Check",
    description:
      "Simple everyday handloom cotton saree in off white with a fine checked pattern, an affordable wardrobe staple.",
    price: 599,
    originalPrice: 999,
    images: [
      "https://images.unsplash.com/photo-1610189025857-f42fe6e8dd91?auto=format&fit=crop&w=1000&h=1300&q=80",
      "https://images.unsplash.com/photo-1610030469668-8e9f641aaf27?auto=format&fit=crop&w=1000&h=1300&q=80",
      "https://images.unsplash.com/photo-1618901185975-d59f7091bcfe?auto=format&fit=crop&w=1000&h=1300&q=80",
    ],
    category: "saree",
    subcategory: "tant",
    fabric: "Cotton",
    color: "Off White Check",
    size: ["Free"],
    stock: 70,
    sku: "SAR-025",
    tags: ["tant", "budget", "saree", "cotton"],
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 9,
  },
  {
    name: "Maroon Silk Embroidered Kurti",
    description:
      "Elegantly crafted maroon silk kurti with intricate thread and zari embroidery on the yoke. Features 3/4 sleeves and mandarin collar.",
    price: 1850,
    originalPrice: 2450,
    images: [
      "https://picsum.photos/seed/kur-001-1/1000/1300",
      "https://picsum.photos/seed/kur-001-2/1000/1300",
      "https://picsum.photos/seed/kur-001-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "straight-fit",
    fabric: "Silk Blend",
    color: "Maroon",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 25,
    sku: "KUR-001",
    tags: ["straight-fit", "kurti", "maroon"],
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 116,
  },
  {
    name: "Mustard Yellow Block Print Cotton Kurti",
    description:
      "Handcrafted pure cotton kurti with traditional Bagru block print in warm mustard yellow and black.",
    price: 1200,
    originalPrice: 1650,
    images: [
      "https://picsum.photos/seed/kur-002-1/1000/1300",
      "https://picsum.photos/seed/kur-002-2/1000/1300",
      "https://picsum.photos/seed/kur-002-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "a-line",
    fabric: "100% Cotton",
    color: "Mustard Yellow",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 21,
    sku: "KUR-002",
    tags: ["a-line", "kurti", "mustard-yellow"],
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 88,
  },
  {
    name: "Emerald Green Chikankari Long Kurti",
    description:
      "Graceful Lucknowi Chikankari hand-embroidered kurti on sheer modal cotton fabric in emerald green.",
    price: 2100,
    originalPrice: 2800,
    images: [
      "https://picsum.photos/seed/kur-003-1/1000/1300",
      "https://picsum.photos/seed/kur-003-2/1000/1300",
      "https://picsum.photos/seed/kur-003-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "chikankari",
    fabric: "Modal Cotton",
    color: "Emerald Green",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 43,
    sku: "KUR-003",
    tags: ["chikankari", "kurti", "emerald-green"],
    isActive: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 116,
  },
  {
    name: "Dusty Rose Rayon Anarkali Kurti",
    description:
      "Flowy flared Anarkali kurti in premium soft rayon with gold foil leaf patterns and a tie-up tassel dori.",
    price: 1650,
    originalPrice: 2199,
    images: [
      "https://picsum.photos/seed/kur-004-1/1000/1300",
      "https://picsum.photos/seed/kur-004-2/1000/1300",
      "https://picsum.photos/seed/kur-004-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "anarkali",
    fabric: "Rayon",
    color: "Dusty Rose",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 22,
    sku: "KUR-004",
    tags: ["anarkali", "kurti", "dusty-rose"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 101,
  },
  {
    name: "Indigo Ikat Print Straight Kurti",
    description:
      "Handwoven Ikat print cotton kurti in indigo with a contemporary straight cut, perfect for casual and office wear.",
    price: 1350,
    originalPrice: 1750,
    images: [
      "https://picsum.photos/seed/kur-005-1/1000/1300",
      "https://picsum.photos/seed/kur-005-2/1000/1300",
      "https://picsum.photos/seed/kur-005-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "straight-fit",
    fabric: "Cotton",
    color: "Indigo",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 31,
    sku: "KUR-005",
    tags: ["straight-fit", "kurti", "indigo"],
    isActive: true,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 23,
  },
  {
    name: "Peach Georgette Layered Kurti",
    description:
      "Soft georgette layered kurti in peach with delicate sequin border, designed for evening and party occasions.",
    price: 1950,
    originalPrice: 2450,
    images: [
      "https://picsum.photos/seed/kur-006-1/1000/1300",
      "https://picsum.photos/seed/kur-006-2/1000/1300",
      "https://picsum.photos/seed/kur-006-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "layered",
    fabric: "Georgette",
    color: "Peach",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 54,
    sku: "KUR-006",
    tags: ["layered", "kurti", "peach"],
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 41,
  },
  {
    name: "Black Rayon Printed Kurti",
    description:
      "Everyday comfort rayon kurti in black with an all-over ethnic motif print, pairs well with jeans or leggings.",
    price: 999,
    originalPrice: 1299,
    images: [
      "https://picsum.photos/seed/kur-007-1/1000/1300",
      "https://picsum.photos/seed/kur-007-2/1000/1300",
      "https://picsum.photos/seed/kur-007-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "straight-fit",
    fabric: "Rayon",
    color: "Black",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 22,
    sku: "KUR-007",
    tags: ["straight-fit", "kurti", "black"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 71,
  },
  {
    name: "Ivory Handloom Cotton Kurti",
    description:
      "Minimalist ivory handloom cotton kurti with subtle woven texture, ideal for warm-weather everyday wear.",
    price: 1150,
    originalPrice: 1499,
    images: [
      "https://picsum.photos/seed/kur-008-1/1000/1300",
      "https://picsum.photos/seed/kur-008-2/1000/1300",
      "https://picsum.photos/seed/kur-008-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "a-line",
    fabric: "Handloom Cotton",
    color: "Ivory",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 46,
    sku: "KUR-008",
    tags: ["a-line", "kurti", "ivory"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 113,
  },
  {
    name: "Coral Chanderi Embroidered Kurti",
    description:
      "Chanderi silk-cotton kurti in coral with fine gota patti embroidery along the neckline and sleeves.",
    price: 2299,
    originalPrice: 2899,
    images: [
      "https://picsum.photos/seed/kur-009-1/1000/1300",
      "https://picsum.photos/seed/kur-009-2/1000/1300",
      "https://picsum.photos/seed/kur-009-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "chanderi",
    fabric: "Chanderi",
    color: "Coral",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 40,
    sku: "KUR-009",
    tags: ["chanderi", "kurti", "coral"],
    isActive: true,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 75,
  },
  {
    name: "Navy Blue Angrakha Style Kurti",
    description:
      "Traditional angrakha style kurti in navy blue cotton with front cross-over tie and contrast piping.",
    price: 1599,
    originalPrice: 1999,
    images: [
      "https://picsum.photos/seed/kur-010-1/1000/1300",
      "https://picsum.photos/seed/kur-010-2/1000/1300",
      "https://picsum.photos/seed/kur-010-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "angrakha",
    fabric: "Cotton",
    color: "Navy Blue",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 16,
    sku: "KUR-010",
    tags: ["angrakha", "kurti", "navy-blue"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 65,
  },
  {
    name: "Sea Blue Bandhani Print Kurti",
    description:
      "Vibrant Bandhani tie-dye print kurti in sea blue and white, a Gujarat craft favourite for festive days.",
    price: 1450,
    originalPrice: 1850,
    images: [
      "https://picsum.photos/seed/kur-011-1/1000/1300",
      "https://picsum.photos/seed/kur-011-2/1000/1300",
      "https://picsum.photos/seed/kur-011-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "bandhani",
    fabric: "Cotton",
    color: "Sea Blue",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 55,
    sku: "KUR-011",
    tags: ["bandhani", "kurti", "sea-blue"],
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 97,
  },
  {
    name: "Beige Linen Straight Kurti",
    description:
      "Breathable linen straight kurti in beige with minimal wooden button detailing, great for summer office wear.",
    price: 1799,
    originalPrice: 2199,
    images: [
      "https://picsum.photos/seed/kur-012-1/1000/1300",
      "https://picsum.photos/seed/kur-012-2/1000/1300",
      "https://picsum.photos/seed/kur-012-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "straight-fit",
    fabric: "Linen",
    color: "Beige",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 53,
    sku: "KUR-012",
    tags: ["straight-fit", "kurti", "beige"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 21,
  },
  {
    name: "Wine Velvet Winter Kurti",
    description:
      "Warm velvet kurti in wine with subtle zari border, designed for festive winter occasions.",
    price: 2599,
    originalPrice: 3199,
    images: [
      "https://picsum.photos/seed/kur-013-1/1000/1300",
      "https://picsum.photos/seed/kur-013-2/1000/1300",
      "https://picsum.photos/seed/kur-013-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "straight-fit",
    fabric: "Velvet",
    color: "Wine",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 35,
    sku: "KUR-013",
    tags: ["straight-fit", "kurti", "wine"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 72,
  },
  {
    name: "Lavender Chikankari Short Kurti",
    description:
      "Short chikankari kurti in soft lavender modal fabric, perfect for pairing with jeans or palazzos.",
    price: 1499,
    originalPrice: 1899,
    images: [
      "https://picsum.photos/seed/kur-014-1/1000/1300",
      "https://picsum.photos/seed/kur-014-2/1000/1300",
      "https://picsum.photos/seed/kur-014-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "chikankari",
    fabric: "Modal Cotton",
    color: "Lavender",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 35,
    sku: "KUR-014",
    tags: ["chikankari", "kurti", "lavender"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 108,
  },
  {
    name: "Rust Orange Kalamkari Print Kurti",
    description:
      "Hand block Kalamkari printed cotton kurti in rust orange with traditional motif storytelling prints.",
    price: 1699,
    originalPrice: 2099,
    images: [
      "https://picsum.photos/seed/kur-015-1/1000/1300",
      "https://picsum.photos/seed/kur-015-2/1000/1300",
      "https://picsum.photos/seed/kur-015-3/1000/1300",
    ],
    category: "kurtis",
    subcategory: "kalamkari",
    fabric: "Cotton",
    color: "Rust Orange",
    size: ["S", "M", "L", "XL", "XXL"],
    stock: 50,
    sku: "KUR-015",
    tags: ["kalamkari", "kurti", "rust-orange"],
    isActive: true,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 40,
  },
  {
    name: "Designer Silk Brocade Blouse - Gold",
    description:
      "Rich silk brocade blouse in antique gold with traditional paisley and floral motifs woven in zari. Structured fit with back hook closure.",
    price: 2199,
    originalPrice: 2699,
    images: [
      "https://picsum.photos/seed/bl-001-1/1000/1300",
      "https://picsum.photos/seed/bl-001-2/1000/1300",
      "https://picsum.photos/seed/bl-001-3/1000/1300",
    ],
    category: "blouses",
    subcategory: "designer",
    fabric: "Silk",
    color: "Antique Gold",
    size: ["S", "M", "L", "XL"],
    stock: 28,
    sku: "BL-001",
    tags: ["designer", "blouse", "antique-gold"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 111,
  },
  {
    name: "Hand Embroidered Cotton Blouse - Floral",
    description:
      "Soft cotton blouse with hand-embroidered floral motifs in pastel threads on ivory base. Sweetheart neckline with back tie-up.",
    price: 1499,
    originalPrice: 1899,
    images: [
      "https://picsum.photos/seed/bl-002-1/1000/1300",
      "https://picsum.photos/seed/bl-002-2/1000/1300",
      "https://picsum.photos/seed/bl-002-3/1000/1300",
    ],
    category: "blouses",
    subcategory: "embroidered",
    fabric: "Cotton",
    color: "Ivory",
    size: ["S", "M", "L", "XL"],
    stock: 36,
    sku: "BL-002",
    tags: ["embroidered", "blouse", "ivory"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 112,
  },
  {
    name: "Mirror Work Blouse - Rani Pink",
    description:
      "Vibrant rani pink blouse with traditional Rajasthani mirror work and thread embroidery on the yoke.",
    price: 1799,
    originalPrice: 2199,
    images: [
      "https://picsum.photos/seed/bl-003-1/1000/1300",
      "https://picsum.photos/seed/bl-003-2/1000/1300",
      "https://picsum.photos/seed/bl-003-3/1000/1300",
    ],
    category: "blouses",
    subcategory: "designer",
    fabric: "Cotton Silk",
    color: "Rani Pink",
    size: ["S", "M", "L", "XL"],
    stock: 56,
    sku: "BL-003",
    tags: ["designer", "blouse", "rani-pink"],
    isActive: true,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 77,
  },
  {
    name: "Velvet Sleeveless Blouse - Bottle Green",
    description:
      "Rich bottle green velvet sleeveless blouse with sequin border, ideal for pairing with silk sarees.",
    price: 1999,
    originalPrice: 2499,
    images: [
      "https://picsum.photos/seed/bl-004-1/1000/1300",
      "https://picsum.photos/seed/bl-004-2/1000/1300",
      "https://picsum.photos/seed/bl-004-3/1000/1300",
    ],
    category: "blouses",
    subcategory: "sleeveless",
    fabric: "Velvet",
    color: "Bottle Green",
    size: ["S", "M", "L", "XL"],
    stock: 27,
    sku: "BL-004",
    tags: ["sleeveless", "blouse", "bottle-green"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 42,
  },
  {
    name: "Net Sheer Sleeve Blouse - Black",
    description:
      "Elegant black blouse with sheer net sleeves and delicate sequin work along the neckline.",
    price: 1699,
    originalPrice: 2099,
    images: [
      "https://picsum.photos/seed/bl-005-1/1000/1300",
      "https://picsum.photos/seed/bl-005-2/1000/1300",
      "https://picsum.photos/seed/bl-005-3/1000/1300",
    ],
    category: "blouses",
    subcategory: "designer",
    fabric: "Net & Silk",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    stock: 27,
    sku: "BL-005",
    tags: ["designer", "blouse", "black"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 76,
  },
  {
    name: "Zardozi Embroidered Blouse - Maroon",
    description:
      "Heavy zardozi embroidered blouse in maroon, crafted for bridal and special occasion sarees.",
    price: 3299,
    originalPrice: 3999,
    images: [
      "https://picsum.photos/seed/bl-006-1/1000/1300",
      "https://picsum.photos/seed/bl-006-2/1000/1300",
      "https://picsum.photos/seed/bl-006-3/1000/1300",
    ],
    category: "blouses",
    subcategory: "bridal",
    fabric: "Silk",
    color: "Maroon",
    size: ["S", "M", "L", "XL"],
    stock: 49,
    sku: "BL-006",
    tags: ["bridal", "blouse", "maroon"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 63,
  },
  {
    name: "Cotton Boat Neck Blouse - Sky Blue",
    description:
      "Comfortable everyday cotton blouse in sky blue with a simple boat neckline and short sleeves.",
    price: 899,
    originalPrice: 1199,
    images: [
      "https://picsum.photos/seed/bl-007-1/1000/1300",
      "https://picsum.photos/seed/bl-007-2/1000/1300",
      "https://picsum.photos/seed/bl-007-3/1000/1300",
    ],
    category: "blouses",
    subcategory: "casual",
    fabric: "Cotton",
    color: "Sky Blue",
    size: ["S", "M", "L", "XL"],
    stock: 33,
    sku: "BL-007",
    tags: ["casual", "blouse", "sky-blue"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 80,
  },
  {
    name: "Sequin Halter Blouse - Champagne",
    description:
      "Contemporary champagne halter-neck blouse with all-over sequin work for party and reception wear.",
    price: 2499,
    originalPrice: 2999,
    images: [
      "https://picsum.photos/seed/bl-008-1/1000/1300",
      "https://picsum.photos/seed/bl-008-2/1000/1300",
      "https://picsum.photos/seed/bl-008-3/1000/1300",
    ],
    category: "blouses",
    subcategory: "party-wear",
    fabric: "Georgette",
    color: "Champagne",
    size: ["S", "M", "L", "XL"],
    stock: 25,
    sku: "BL-008",
    tags: ["party-wear", "blouse", "champagne"],
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 87,
  },
  {
    name: "Bridal Velvet Lehenga - Deep Red",
    description:
      "Opulent bridal lehenga in deep red velvet with heavy gold zari embroidery and sequin work. Includes matching choli and dupatta.",
    price: 24999,
    originalPrice: 29999,
    images: [
      "https://picsum.photos/seed/leh-001-1/1000/1300",
      "https://picsum.photos/seed/leh-001-2/1000/1300",
      "https://picsum.photos/seed/leh-001-3/1000/1300",
    ],
    category: "lehenga",
    subcategory: "bridal",
    fabric: "Velvet",
    color: "Deep Red",
    size: ["S", "M", "L", "XL"],
    stock: 28,
    sku: "LEH-001",
    tags: ["bridal", "lehenga", "deep-red"],
    isActive: true,
    isFeatured: true,
    rating: 4.5,
    reviewCount: 46,
  },
  {
    name: "Georgette Lehenga Choli - Mint Green",
    description:
      "Lightweight georgette lehenga in refreshing mint green with silver thread embroidery and mirror work.",
    price: 15999,
    originalPrice: 18999,
    images: [
      "https://picsum.photos/seed/leh-002-1/1000/1300",
      "https://picsum.photos/seed/leh-002-2/1000/1300",
      "https://picsum.photos/seed/leh-002-3/1000/1300",
    ],
    category: "lehenga",
    subcategory: "party",
    fabric: "Georgette",
    color: "Mint Green",
    size: ["S", "M", "L", "XL"],
    stock: 6,
    sku: "LEH-002",
    tags: ["party", "lehenga", "mint-green"],
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 46,
  },
  {
    name: "Silk Lehenga Choli - Peacock Blue",
    description:
      "Rich peacock blue silk lehenga with gold zari border and matching embroidered blouse, perfect for receptions.",
    price: 18999,
    originalPrice: 22999,
    images: [
      "https://picsum.photos/seed/leh-003-1/1000/1300",
      "https://picsum.photos/seed/leh-003-2/1000/1300",
      "https://picsum.photos/seed/leh-003-3/1000/1300",
    ],
    category: "lehenga",
    subcategory: "party",
    fabric: "Silk",
    color: "Peacock Blue",
    size: ["S", "M", "L", "XL"],
    stock: 11,
    sku: "LEH-003",
    tags: ["party", "lehenga", "peacock-blue"],
    isActive: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 10,
  },
  {
    name: "Net Embroidered Lehenga - Blush Pink",
    description:
      "Delicate blush pink net lehenga with floral thread embroidery and scalloped hemline, ideal for sangeet.",
    price: 13999,
    originalPrice: 16999,
    images: [
      "https://picsum.photos/seed/leh-004-1/1000/1300",
      "https://picsum.photos/seed/leh-004-2/1000/1300",
      "https://picsum.photos/seed/leh-004-3/1000/1300",
    ],
    category: "lehenga",
    subcategory: "sangeet",
    fabric: "Net",
    color: "Blush Pink",
    size: ["S", "M", "L", "XL"],
    stock: 10,
    sku: "LEH-004",
    tags: ["sangeet", "lehenga", "blush-pink"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 30,
  },
  {
    name: "Banarasi Silk Lehenga - Emerald Gold",
    description:
      "Traditional Banarasi silk lehenga in emerald green with woven gold motifs, includes matching dupatta.",
    price: 21999,
    originalPrice: 25999,
    images: [
      "https://picsum.photos/seed/leh-005-1/1000/1300",
      "https://picsum.photos/seed/leh-005-2/1000/1300",
      "https://picsum.photos/seed/leh-005-3/1000/1300",
    ],
    category: "lehenga",
    subcategory: "bridal",
    fabric: "Banarasi Silk",
    color: "Emerald Gold",
    size: ["S", "M", "L", "XL"],
    stock: 25,
    sku: "LEH-005",
    tags: ["bridal", "lehenga", "emerald-gold"],
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 40,
  },
  {
    name: "Organza Floral Lehenga - Lilac",
    description:
      "Soft organza lehenga in lilac with 3D floral appliqué work, designed for daytime wedding functions.",
    price: 12999,
    originalPrice: 15999,
    images: [
      "https://picsum.photos/seed/leh-006-1/1000/1300",
      "https://picsum.photos/seed/leh-006-2/1000/1300",
      "https://picsum.photos/seed/leh-006-3/1000/1300",
    ],
    category: "lehenga",
    subcategory: "party",
    fabric: "Organza",
    color: "Lilac",
    size: ["S", "M", "L", "XL"],
    stock: 13,
    sku: "LEH-006",
    tags: ["party", "lehenga", "lilac"],
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 40,
  },
  {
    name: "Sequin Party Lehenga - Black Gold",
    description:
      "Glamorous black lehenga with all-over gold sequin work, perfect for sangeet or cocktail parties.",
    price: 16999,
    originalPrice: 19999,
    images: [
      "https://picsum.photos/seed/leh-007-1/1000/1300",
      "https://picsum.photos/seed/leh-007-2/1000/1300",
      "https://picsum.photos/seed/leh-007-3/1000/1300",
    ],
    category: "lehenga",
    subcategory: "party",
    fabric: "Georgette",
    color: "Black & Gold",
    size: ["S", "M", "L", "XL"],
    stock: 12,
    sku: "LEH-007",
    tags: ["party", "lehenga", "black-&-gold"],
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 34,
  },
  {
    name: "Kids Lehenga Choli - Coral Pink",
    description:
      "Adorable coral pink lehenga choli set for young girls with mirror work and comfortable elastic waist.",
    price: 2499,
    originalPrice: 2999,
    images: [
      "https://picsum.photos/seed/leh-008-1/1000/1300",
      "https://picsum.photos/seed/leh-008-2/1000/1300",
      "https://picsum.photos/seed/leh-008-3/1000/1300",
    ],
    category: "lehenga",
    subcategory: "kids",
    fabric: "Georgette",
    color: "Coral Pink",
    size: ["2-3Y", "4-5Y", "6-7Y"],
    stock: 8,
    sku: "LEH-008",
    tags: ["kids", "lehenga", "coral-pink"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 12,
  },
  {
    name: "Chiffon Dupatta - Gold Zari Border",
    description:
      "Sheer chiffon dupatta in soft ivory with wide gold zari border on all four sides.",
    price: 1899,
    originalPrice: 2299,
    images: [
      "https://picsum.photos/seed/dup-001-1/1000/1300",
      "https://picsum.photos/seed/dup-001-2/1000/1300",
      "https://picsum.photos/seed/dup-001-3/1000/1300",
    ],
    category: "dupatta",
    subcategory: "chiffon",
    fabric: "Chiffon",
    color: "Ivory with Gold Border",
    size: ["Free"],
    stock: 18,
    sku: "DUP-001",
    tags: ["chiffon", "dupatta", "ivory-with-gold-border"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 19,
  },
  {
    name: "Hand-Painted Silk Dupatta - Floral",
    description:
      "Premium silk dupatta hand-painted with delicate floral motifs in natural dyes on a teal base.",
    price: 3499,
    originalPrice: 4199,
    images: [
      "https://picsum.photos/seed/dup-002-1/1000/1300",
      "https://picsum.photos/seed/dup-002-2/1000/1300",
      "https://picsum.photos/seed/dup-002-3/1000/1300",
    ],
    category: "dupatta",
    subcategory: "hand-painted",
    fabric: "Silk",
    color: "Teal with Floral Art",
    size: ["Free"],
    stock: 15,
    sku: "DUP-002",
    tags: ["hand-painted", "dupatta", "teal-with-floral-art"],
    isActive: true,
    isFeatured: false,
    rating: 4.1,
    reviewCount: 32,
  },
  {
    name: "Phulkari Embroidered Dupatta - Orange",
    description:
      "Vibrant Punjab Phulkari hand-embroidered dupatta in orange with traditional geometric floral thread work.",
    price: 2199,
    originalPrice: 2699,
    images: [
      "https://picsum.photos/seed/dup-003-1/1000/1300",
      "https://picsum.photos/seed/dup-003-2/1000/1300",
      "https://picsum.photos/seed/dup-003-3/1000/1300",
    ],
    category: "dupatta",
    subcategory: "phulkari",
    fabric: "Cotton",
    color: "Orange",
    size: ["Free"],
    stock: 21,
    sku: "DUP-003",
    tags: ["phulkari", "dupatta", "orange"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 38,
  },
  {
    name: "Net Dupatta with Lace Border - White",
    description:
      "Elegant white net dupatta with delicate lace border, perfect for pairing with anarkalis and gowns.",
    price: 1299,
    originalPrice: 1599,
    images: [
      "https://picsum.photos/seed/dup-004-1/1000/1300",
      "https://picsum.photos/seed/dup-004-2/1000/1300",
      "https://picsum.photos/seed/dup-004-3/1000/1300",
    ],
    category: "dupatta",
    subcategory: "net",
    fabric: "Net",
    color: "White",
    size: ["Free"],
    stock: 29,
    sku: "DUP-004",
    tags: ["net", "dupatta", "white"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 29,
  },
  {
    name: "Bandhani Silk Dupatta - Magenta",
    description:
      "Traditional Bandhani tie-dye silk dupatta in bold magenta and yellow, a Rajasthan craft classic.",
    price: 1999,
    originalPrice: 2399,
    images: [
      "https://picsum.photos/seed/dup-005-1/1000/1300",
      "https://picsum.photos/seed/dup-005-2/1000/1300",
      "https://picsum.photos/seed/dup-005-3/1000/1300",
    ],
    category: "dupatta",
    subcategory: "bandhani",
    fabric: "Silk",
    color: "Magenta",
    size: ["Free"],
    stock: 47,
    sku: "DUP-005",
    tags: ["bandhani", "dupatta", "magenta"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 21,
  },
  {
    name: "Organza Sequin Dupatta - Silver",
    description:
      "Sheer organza dupatta in silver grey with fine sequin scatter, adds shimmer to any festive outfit.",
    price: 2299,
    originalPrice: 2799,
    images: [
      "https://picsum.photos/seed/dup-006-1/1000/1300",
      "https://picsum.photos/seed/dup-006-2/1000/1300",
      "https://picsum.photos/seed/dup-006-3/1000/1300",
    ],
    category: "dupatta",
    subcategory: "organza",
    fabric: "Organza",
    color: "Silver Grey",
    size: ["Free"],
    stock: 47,
    sku: "DUP-006",
    tags: ["organza", "dupatta", "silver-grey"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 25,
  },
  {
    name: "Cotton Block Print Dupatta - Indigo",
    description:
      "Hand block printed cotton dupatta in indigo with traditional Ajrakh motifs, a versatile everyday piece.",
    price: 999,
    originalPrice: 1299,
    images: [
      "https://picsum.photos/seed/dup-007-1/1000/1300",
      "https://picsum.photos/seed/dup-007-2/1000/1300",
      "https://picsum.photos/seed/dup-007-3/1000/1300",
    ],
    category: "dupatta",
    subcategory: "block-print",
    fabric: "Cotton",
    color: "Indigo",
    size: ["Free"],
    stock: 47,
    sku: "DUP-007",
    tags: ["block-print", "dupatta", "indigo"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 22,
  },
  {
    name: "Tissue Silk Dupatta - Rose Gold",
    description:
      "Luminous tissue silk dupatta in rose gold with a delicate zari border, ideal for evening functions.",
    price: 2799,
    originalPrice: 3299,
    images: [
      "https://picsum.photos/seed/dup-008-1/1000/1300",
      "https://picsum.photos/seed/dup-008-2/1000/1300",
      "https://picsum.photos/seed/dup-008-3/1000/1300",
    ],
    category: "dupatta",
    subcategory: "tissue",
    fabric: "Tissue Silk",
    color: "Rose Gold",
    size: ["Free"],
    stock: 41,
    sku: "DUP-008",
    tags: ["tissue", "dupatta", "rose-gold"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 30,
  },
  {
    name: "Oxidized Silver Jhumkas - Traditional",
    description:
      "Handcrafted oxidized silver jhumkas with traditional dome shape and intricate filigree work.",
    price: 899,
    originalPrice: 1199,
    images: [
      "https://picsum.photos/seed/acc-001-1/1000/1300",
      "https://picsum.photos/seed/acc-001-2/1000/1300",
      "https://picsum.photos/seed/acc-001-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "earrings",
    fabric: "Metal",
    color: "Oxidized Silver",
    size: ["Free"],
    stock: 36,
    sku: "ACC-001",
    tags: ["earrings", "accessories", "oxidized-silver"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 107,
  },
  {
    name: "Pearl Kundan Necklace Set - Bridal",
    description:
      "Exquisite bridal necklace set featuring freshwater pearls and kundan stones set in gold-plated brass.",
    price: 4999,
    originalPrice: 5999,
    images: [
      "https://picsum.photos/seed/acc-002-1/1000/1300",
      "https://picsum.photos/seed/acc-002-2/1000/1300",
      "https://picsum.photos/seed/acc-002-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "necklace-set",
    fabric: "Pearl/Brass",
    color: "Gold with Pearls",
    size: ["Free"],
    stock: 48,
    sku: "ACC-002",
    tags: ["necklace-set", "accessories", "gold-with-pearls"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 129,
  },
  {
    name: "Temple Jewellery Necklace Set - Antique Gold",
    description:
      "Traditional South Indian temple jewellery necklace set with goddess motifs in antique gold finish.",
    price: 3799,
    originalPrice: 4499,
    images: [
      "https://picsum.photos/seed/acc-003-1/1000/1300",
      "https://picsum.photos/seed/acc-003-2/1000/1300",
      "https://picsum.photos/seed/acc-003-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "necklace-set",
    fabric: "Brass",
    color: "Antique Gold",
    size: ["Free"],
    stock: 26,
    sku: "ACC-003",
    tags: ["necklace-set", "accessories", "antique-gold"],
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 118,
  },
  {
    name: "Glass Bangles Set - Multicolor",
    description:
      "Set of 24 traditional glass bangles in multicolor, perfect for festive and bridal occasions.",
    price: 499,
    originalPrice: 699,
    images: [
      "https://picsum.photos/seed/acc-004-1/1000/1300",
      "https://picsum.photos/seed/acc-004-2/1000/1300",
      "https://picsum.photos/seed/acc-004-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "bangles",
    fabric: "Glass",
    color: "Multicolor",
    size: ["Free"],
    stock: 21,
    sku: "ACC-004",
    tags: ["bangles", "accessories", "multicolor"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 122,
  },
  {
    name: "Meenakari Jhumka Earrings - Peacock Green",
    description:
      "Colorful Meenakari enamel work jhumkas in peacock green and pink, handcrafted by Jaipur artisans.",
    price: 1099,
    originalPrice: 1399,
    images: [
      "https://picsum.photos/seed/acc-005-1/1000/1300",
      "https://picsum.photos/seed/acc-005-2/1000/1300",
      "https://picsum.photos/seed/acc-005-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "earrings",
    fabric: "Metal & Enamel",
    color: "Peacock Green",
    size: ["Free"],
    stock: 75,
    sku: "ACC-005",
    tags: ["earrings", "accessories", "peacock-green"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 26,
  },
  {
    name: "Kundan Maang Tikka - Bridal Gold",
    description:
      "Delicate kundan and pearl maang tikka in gold finish, a must-have bridal hair accessory.",
    price: 799,
    originalPrice: 999,
    images: [
      "https://picsum.photos/seed/acc-006-1/1000/1300",
      "https://picsum.photos/seed/acc-006-2/1000/1300",
      "https://picsum.photos/seed/acc-006-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "maang-tikka",
    fabric: "Brass/Kundan",
    color: "Gold",
    size: ["Free"],
    stock: 45,
    sku: "ACC-006",
    tags: ["maang-tikka", "accessories", "gold"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 74,
  },
  {
    name: "Silver Anklets Pair - Ghungroo Bells",
    description:
      "Traditional silver-toned anklet pair with tiny ghungroo bells, adds a melodic charm to every step.",
    price: 649,
    originalPrice: 849,
    images: [
      "https://picsum.photos/seed/acc-007-1/1000/1300",
      "https://picsum.photos/seed/acc-007-2/1000/1300",
      "https://picsum.photos/seed/acc-007-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "anklets",
    fabric: "Metal",
    color: "Silver",
    size: ["Free"],
    stock: 38,
    sku: "ACC-007",
    tags: ["anklets", "accessories", "silver"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 57,
  },
  {
    name: "Beaded Potli Bag - Maroon",
    description:
      "Hand-beaded maroon potli bag with drawstring closure, a perfect companion for sarees and lehengas.",
    price: 899,
    originalPrice: 1099,
    images: [
      "https://picsum.photos/seed/acc-008-1/1000/1300",
      "https://picsum.photos/seed/acc-008-2/1000/1300",
      "https://picsum.photos/seed/acc-008-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "bags",
    fabric: "Silk & Beads",
    color: "Maroon",
    size: ["Free"],
    stock: 26,
    sku: "ACC-008",
    tags: ["bags", "accessories", "maroon"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 127,
  },
  {
    name: "Nath Nose Ring - Pearl Gold",
    description:
      "Traditional pearl-studded gold-toned nath, adjustable to fit comfortably without piercing.",
    price: 599,
    originalPrice: 799,
    images: [
      "https://picsum.photos/seed/acc-009-1/1000/1300",
      "https://picsum.photos/seed/acc-009-2/1000/1300",
      "https://picsum.photos/seed/acc-009-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "nose-ring",
    fabric: "Brass/Pearl",
    color: "Gold",
    size: ["Free"],
    stock: 27,
    sku: "ACC-009",
    tags: ["nose-ring", "accessories", "gold"],
    isActive: true,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 126,
  },
  {
    name: "Layered Choker Necklace - Rose Gold",
    description:
      "Modern layered choker necklace in rose gold finish with cubic zirconia detailing, great for fusion wear.",
    price: 1299,
    originalPrice: 1599,
    images: [
      "https://picsum.photos/seed/acc-010-1/1000/1300",
      "https://picsum.photos/seed/acc-010-2/1000/1300",
      "https://picsum.photos/seed/acc-010-3/1000/1300",
    ],
    category: "accessories",
    subcategory: "necklace-set",
    fabric: "Alloy",
    color: "Rose Gold",
    size: ["Free"],
    stock: 23,
    sku: "ACC-010",
    tags: ["necklace-set", "accessories", "rose-gold"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 130,
  },
  {
    name: "Handloom Tussar Silk Kurta & Pyjama Set",
    description:
      "Classic men's Tussar silk kurta in natural beige with thread embroidery on the placket and cuffs. Comes with matching churidar pyjama.",
    price: 3899,
    originalPrice: 4599,
    images: [
      "https://picsum.photos/seed/men-001-1/1000/1300",
      "https://picsum.photos/seed/men-001-2/1000/1300",
      "https://picsum.photos/seed/men-001-3/1000/1300",
    ],
    category: "menswear",
    subcategory: "kurta-set",
    fabric: "Tussar Silk",
    color: "Natural Beige",
    size: ["38", "40", "42", "44", "46"],
    stock: 27,
    sku: "MEN-001",
    tags: ["kurta-set", "menswear", "natural-beige"],
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 27,
  },
  {
    name: "Cotton Silk Kurta - Off White",
    description:
      "Comfortable off-white cotton silk kurta with mandarin collar, suited for daily wear and casual pujas.",
    price: 1599,
    originalPrice: 1999,
    images: [
      "https://picsum.photos/seed/men-002-1/1000/1300",
      "https://picsum.photos/seed/men-002-2/1000/1300",
      "https://picsum.photos/seed/men-002-3/1000/1300",
    ],
    category: "menswear",
    subcategory: "kurta",
    fabric: "Cotton Silk",
    color: "Off White",
    size: ["38", "40", "42", "44", "46"],
    stock: 21,
    sku: "MEN-002",
    tags: ["kurta", "menswear", "off-white"],
    isActive: true,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 62,
  },
  {
    name: "Nehru Jacket - Maroon Brocade",
    description:
      "Festive maroon brocade Nehru jacket with woven gold motifs, pairs well over kurtas for weddings.",
    price: 2499,
    originalPrice: 2999,
    images: [
      "https://picsum.photos/seed/men-003-1/1000/1300",
      "https://picsum.photos/seed/men-003-2/1000/1300",
      "https://picsum.photos/seed/men-003-3/1000/1300",
    ],
    category: "menswear",
    subcategory: "jacket",
    fabric: "Brocade",
    color: "Maroon",
    size: ["38", "40", "42", "44", "46"],
    stock: 19,
    sku: "MEN-003",
    tags: ["jacket", "menswear", "maroon"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 56,
  },
  {
    name: "Linen Kurta - Sky Blue",
    description:
      "Breathable linen kurta in sky blue, designed for summer comfort with a relaxed straight fit.",
    price: 1399,
    originalPrice: 1699,
    images: [
      "https://picsum.photos/seed/men-004-1/1000/1300",
      "https://picsum.photos/seed/men-004-2/1000/1300",
      "https://picsum.photos/seed/men-004-3/1000/1300",
    ],
    category: "menswear",
    subcategory: "kurta",
    fabric: "Linen",
    color: "Sky Blue",
    size: ["38", "40", "42", "44", "46"],
    stock: 39,
    sku: "MEN-004",
    tags: ["kurta", "menswear", "sky-blue"],
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 19,
  },
  {
    name: "Silk Dhoti & Kurta Set - Cream Gold",
    description:
      "Traditional cream and gold silk dhoti kurta set for pujas and festive ceremonies.",
    price: 4499,
    originalPrice: 5299,
    images: [
      "https://picsum.photos/seed/men-005-1/1000/1300",
      "https://picsum.photos/seed/men-005-2/1000/1300",
      "https://picsum.photos/seed/men-005-3/1000/1300",
    ],
    category: "menswear",
    subcategory: "dhoti-set",
    fabric: "Silk",
    color: "Cream & Gold",
    size: ["38", "40", "42", "44", "46"],
    stock: 31,
    sku: "MEN-005",
    tags: ["dhoti-set", "menswear", "cream-&-gold"],
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 44,
  },
  {
    name: "Printed Cotton Kurta - Indigo",
    description:
      "Casual indigo cotton kurta with subtle block print detailing, great for everyday ethnic wear.",
    price: 1099,
    originalPrice: 1399,
    images: [
      "https://picsum.photos/seed/men-006-1/1000/1300",
      "https://picsum.photos/seed/men-006-2/1000/1300",
      "https://picsum.photos/seed/men-006-3/1000/1300",
    ],
    category: "menswear",
    subcategory: "kurta",
    fabric: "Cotton",
    color: "Indigo",
    size: ["38", "40", "42", "44", "46"],
    stock: 24,
    sku: "MEN-006",
    tags: ["kurta", "menswear", "indigo"],
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 63,
  },
  {
    name: "Bandhgala Suit - Charcoal Grey",
    description:
      "Sophisticated charcoal grey Bandhgala suit for weddings and formal ethnic occasions.",
    price: 6999,
    originalPrice: 8299,
    images: [
      "https://picsum.photos/seed/men-007-1/1000/1300",
      "https://picsum.photos/seed/men-007-2/1000/1300",
      "https://picsum.photos/seed/men-007-3/1000/1300",
    ],
    category: "menswear",
    subcategory: "bandhgala",
    fabric: "Wool Blend",
    color: "Charcoal Grey",
    size: ["38", "40", "42", "44", "46"],
    stock: 43,
    sku: "MEN-007",
    tags: ["bandhgala", "menswear", "charcoal-grey"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 55,
  },
  {
    name: "Cotton Pyjama - White",
    description:
      "Soft breathable cotton pyjama in white, a comfortable everyday pairing for kurtas.",
    price: 599,
    originalPrice: 799,
    images: [
      "https://picsum.photos/seed/men-008-1/1000/1300",
      "https://picsum.photos/seed/men-008-2/1000/1300",
      "https://picsum.photos/seed/men-008-3/1000/1300",
    ],
    category: "menswear",
    subcategory: "bottomwear",
    fabric: "Cotton",
    color: "White",
    size: ["38", "40", "42", "44", "46"],
    stock: 40,
    sku: "MEN-008",
    tags: ["bottomwear", "menswear", "white"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 41,
  },
  {
    name: "Chanderi Silk Salwar Suit Set - Royal Navy",
    description:
      "Unstitched Chanderi silk suit material with hand-block print kurta fabric, soft santoon bottom, and zari border Chanderi dupatta.",
    price: 3499,
    originalPrice: 4299,
    images: [
      "https://picsum.photos/seed/suit-001-1/1000/1300",
      "https://picsum.photos/seed/suit-001-2/1000/1300",
      "https://picsum.photos/seed/suit-001-3/1000/1300",
    ],
    category: "salwar-suits",
    subcategory: "unstitched",
    fabric: "Chanderi Silk",
    color: "Navy Blue",
    size: ["Unstitched"],
    stock: 21,
    sku: "SUIT-001",
    tags: ["unstitched", "salwar-suit", "navy-blue"],
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 31,
  },
  {
    name: "Cotton Printed Salwar Suit - Peach Floral",
    description:
      "Unstitched cotton salwar suit set with peach floral print kurta fabric and matching cotton dupatta.",
    price: 1899,
    originalPrice: 2299,
    images: [
      "https://picsum.photos/seed/suit-002-1/1000/1300",
      "https://picsum.photos/seed/suit-002-2/1000/1300",
      "https://picsum.photos/seed/suit-002-3/1000/1300",
    ],
    category: "salwar-suits",
    subcategory: "unstitched",
    fabric: "Cotton",
    color: "Peach Floral",
    size: ["Unstitched"],
    stock: 30,
    sku: "SUIT-002",
    tags: ["unstitched", "salwar-suit", "peach-floral"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 42,
  },
  {
    name: "Georgette Embroidered Suit Set - Mint",
    description:
      "Semi-stitched georgette suit set in mint with thread embroidery on the yoke and net dupatta.",
    price: 2999,
    originalPrice: 3599,
    images: [
      "https://picsum.photos/seed/suit-003-1/1000/1300",
      "https://picsum.photos/seed/suit-003-2/1000/1300",
      "https://picsum.photos/seed/suit-003-3/1000/1300",
    ],
    category: "salwar-suits",
    subcategory: "semi-stitched",
    fabric: "Georgette",
    color: "Mint",
    size: ["Unstitched"],
    stock: 44,
    sku: "SUIT-003",
    tags: ["semi-stitched", "salwar-suit", "mint"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 57,
  },
  {
    name: "Cotton Silk Suit Set - Rust",
    description:
      "Unstitched cotton silk suit material in rust with woven border, ideal for festive daily wear.",
    price: 2199,
    originalPrice: 2699,
    images: [
      "https://picsum.photos/seed/suit-004-1/1000/1300",
      "https://picsum.photos/seed/suit-004-2/1000/1300",
      "https://picsum.photos/seed/suit-004-3/1000/1300",
    ],
    category: "salwar-suits",
    subcategory: "unstitched",
    fabric: "Cotton Silk",
    color: "Rust",
    size: ["Unstitched"],
    stock: 18,
    sku: "SUIT-004",
    tags: ["unstitched", "salwar-suit", "rust"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 27,
  },
  {
    name: "Muslin Cotton Suit Set - Sky Blue",
    description:
      "Lightweight muslin cotton suit set in sky blue with hand block print, includes matching dupatta.",
    price: 2499,
    originalPrice: 2999,
    images: [
      "https://picsum.photos/seed/suit-005-1/1000/1300",
      "https://picsum.photos/seed/suit-005-2/1000/1300",
      "https://picsum.photos/seed/suit-005-3/1000/1300",
    ],
    category: "salwar-suits",
    subcategory: "unstitched",
    fabric: "Muslin Cotton",
    color: "Sky Blue",
    size: ["Unstitched"],
    stock: 45,
    sku: "SUIT-005",
    tags: ["unstitched", "salwar-suit", "sky-blue"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 51,
  },
  {
    name: "Anarkali Suit Set - Wine Velvet",
    description:
      "Ready-to-wear wine velvet Anarkali suit set with gold embroidery, perfect for winter festivities.",
    price: 4999,
    originalPrice: 5999,
    images: [
      "https://picsum.photos/seed/suit-006-1/1000/1300",
      "https://picsum.photos/seed/suit-006-2/1000/1300",
      "https://picsum.photos/seed/suit-006-3/1000/1300",
    ],
    category: "salwar-suits",
    subcategory: "readymade",
    fabric: "Velvet",
    color: "Wine",
    size: ["S", "M", "L", "XL"],
    stock: 44,
    sku: "SUIT-006",
    tags: ["readymade", "salwar-suit", "wine"],
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 22,
  },
  {
    name: "Chikankari Suit Set - Ivory",
    description:
      "Delicate Lucknowi Chikankari suit set on ivory cotton fabric with matching chiffon dupatta.",
    price: 2799,
    originalPrice: 3399,
    images: [
      "https://picsum.photos/seed/suit-007-1/1000/1300",
      "https://picsum.photos/seed/suit-007-2/1000/1300",
      "https://picsum.photos/seed/suit-007-3/1000/1300",
    ],
    category: "salwar-suits",
    subcategory: "unstitched",
    fabric: "Cotton",
    color: "Ivory",
    size: ["Unstitched"],
    stock: 47,
    sku: "SUIT-007",
    tags: ["unstitched", "salwar-suit", "ivory"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 31,
  },
  {
    name: "Patiala Suit Set - Yellow Cotton",
    description:
      "Classic Patiala salwar suit set in cheerful yellow cotton with contrast phulkari dupatta.",
    price: 1799,
    originalPrice: 2199,
    images: [
      "https://picsum.photos/seed/suit-008-1/1000/1300",
      "https://picsum.photos/seed/suit-008-2/1000/1300",
      "https://picsum.photos/seed/suit-008-3/1000/1300",
    ],
    category: "salwar-suits",
    subcategory: "patiala",
    fabric: "Cotton",
    color: "Yellow",
    size: ["Unstitched"],
    stock: 42,
    sku: "SUIT-008",
    tags: ["patiala", "salwar-suit", "yellow"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 56,
  },
  {
    name: "Pure Cotton Hand-Batik Nighty",
    description:
      "100% combed cotton nightdress with traditional Santiniketan hand batik art. Soft, roomy, and ultra-breathable.",
    price: 799,
    originalPrice: 999,
    images: [
      "https://picsum.photos/seed/ngt-001-1/1000/1300",
      "https://picsum.photos/seed/ngt-001-2/1000/1300",
      "https://picsum.photos/seed/ngt-001-3/1000/1300",
    ],
    category: "nighties",
    subcategory: "cotton-nighty",
    fabric: "100% Cotton",
    color: "Indigo & Maroon",
    size: ["Free", "XL", "XXL"],
    stock: 55,
    sku: "NGT-001",
    tags: ["cotton-nighty", "nighty", "indigo-&-maroon"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 79,
  },
  {
    name: "Floral Print Cotton Nighty - Pastel",
    description:
      "Comfortable pastel floral print cotton nighty with front button placket and side pockets.",
    price: 649,
    originalPrice: 849,
    images: [
      "https://picsum.photos/seed/ngt-002-1/1000/1300",
      "https://picsum.photos/seed/ngt-002-2/1000/1300",
      "https://picsum.photos/seed/ngt-002-3/1000/1300",
    ],
    category: "nighties",
    subcategory: "cotton-nighty",
    fabric: "Cotton",
    color: "Pastel Floral",
    size: ["Free", "XL", "XXL"],
    stock: 39,
    sku: "NGT-002",
    tags: ["cotton-nighty", "nighty", "pastel-floral"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 91,
  },
  {
    name: "Satin Nighty with Robe - Wine",
    description:
      "Luxurious wine satin nighty and robe set, smooth on skin and perfect for gifting.",
    price: 1299,
    originalPrice: 1599,
    images: [
      "https://picsum.photos/seed/ngt-003-1/1000/1300",
      "https://picsum.photos/seed/ngt-003-2/1000/1300",
      "https://picsum.photos/seed/ngt-003-3/1000/1300",
    ],
    category: "nighties",
    subcategory: "satin-nighty",
    fabric: "Satin",
    color: "Wine",
    size: ["Free", "XL", "XXL"],
    stock: 84,
    sku: "NGT-003",
    tags: ["satin-nighty", "nighty", "wine"],
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 34,
  },
  {
    name: "Cotton Maxi Nighty - Sky Blue",
    description:
      "Loose-fit cotton maxi nighty in sky blue with lace trim at the neckline for everyday comfort.",
    price: 699,
    originalPrice: 899,
    images: [
      "https://picsum.photos/seed/ngt-004-1/1000/1300",
      "https://picsum.photos/seed/ngt-004-2/1000/1300",
      "https://picsum.photos/seed/ngt-004-3/1000/1300",
    ],
    category: "nighties",
    subcategory: "cotton-nighty",
    fabric: "Cotton",
    color: "Sky Blue",
    size: ["Free", "XL", "XXL"],
    stock: 72,
    sku: "NGT-004",
    tags: ["cotton-nighty", "nighty", "sky-blue"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 106,
  },
  {
    name: "Printed Rayon Nighty - Mustard",
    description:
      "Breezy rayon nighty in mustard floral print, lightweight and quick-drying for daily wear.",
    price: 749,
    originalPrice: 949,
    images: [
      "https://picsum.photos/seed/ngt-005-1/1000/1300",
      "https://picsum.photos/seed/ngt-005-2/1000/1300",
      "https://picsum.photos/seed/ngt-005-3/1000/1300",
    ],
    category: "nighties",
    subcategory: "rayon-nighty",
    fabric: "Rayon",
    color: "Mustard",
    size: ["Free", "XL", "XXL"],
    stock: 31,
    sku: "NGT-005",
    tags: ["rayon-nighty", "nighty", "mustard"],
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 88,
  },
  {
    name: "Cotton Hosiery Nighty - Grey Melange",
    description:
      "Everyday cotton hosiery nighty in grey melange, stretchable and soft for a comfortable night's sleep.",
    price: 599,
    originalPrice: 799,
    images: [
      "https://picsum.photos/seed/ngt-006-1/1000/1300",
      "https://picsum.photos/seed/ngt-006-2/1000/1300",
      "https://picsum.photos/seed/ngt-006-3/1000/1300",
    ],
    category: "nighties",
    subcategory: "cotton-nighty",
    fabric: "Cotton Hosiery",
    color: "Grey Melange",
    size: ["Free", "XL", "XXL"],
    stock: 53,
    sku: "NGT-006",
    tags: ["cotton-nighty", "nighty", "grey-melange"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 127,
  },
  {
    name: "Batik Print Nighty - Sea Green",
    description:
      "Hand batik printed cotton nighty in sea green with front zipper and roomy fit.",
    price: 799,
    originalPrice: 999,
    images: [
      "https://picsum.photos/seed/ngt-007-1/1000/1300",
      "https://picsum.photos/seed/ngt-007-2/1000/1300",
      "https://picsum.photos/seed/ngt-007-3/1000/1300",
    ],
    category: "nighties",
    subcategory: "cotton-nighty",
    fabric: "Cotton",
    color: "Sea Green",
    size: ["Free", "XL", "XXL"],
    stock: 52,
    sku: "NGT-007",
    tags: ["cotton-nighty", "nighty", "sea-green"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 115,
  },
  {
    name: "Nursing Nighty - Dusty Pink",
    description:
      "Comfortable dusty pink nursing nighty with easy-access zippers, designed for new mothers.",
    price: 849,
    originalPrice: 1049,
    images: [
      "https://picsum.photos/seed/ngt-008-1/1000/1300",
      "https://picsum.photos/seed/ngt-008-2/1000/1300",
      "https://picsum.photos/seed/ngt-008-3/1000/1300",
    ],
    category: "nighties",
    subcategory: "nursing",
    fabric: "Cotton",
    color: "Dusty Pink",
    size: ["Free", "XL", "XXL"],
    stock: 36,
    sku: "NGT-008",
    tags: ["nursing", "nighty", "dusty-pink"],
    isActive: true,
    isFeatured: false,
    rating: 4.2,
    reviewCount: 90,
  },
  {
    name: "Kids Handloom Dhoti Kurta Set - Maroon",
    description:
      "Traditional pure cotton dhoti kurta set for boys with soft elasticated waistband dhoti and embroidered mandarin collar kurta.",
    price: 1299,
    originalPrice: 1599,
    images: [
      "https://picsum.photos/seed/kid-001-1/1000/1300",
      "https://picsum.photos/seed/kid-001-2/1000/1300",
      "https://picsum.photos/seed/kid-001-3/1000/1300",
    ],
    category: "kids-wear",
    subcategory: "boys-ethnic",
    fabric: "Pure Cotton",
    color: "Maroon & Cream",
    size: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    stock: 40,
    sku: "KID-001",
    tags: ["boys-ethnic", "kids-wear", "maroon-&-cream"],
    isActive: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 30,
  },
  {
    name: "Girls Lehenga Choli - Peacock Blue",
    description:
      "Vibrant peacock blue lehenga choli for girls with mirror work, perfect for festivals and family functions.",
    price: 1799,
    originalPrice: 2199,
    images: [
      "https://picsum.photos/seed/kid-002-1/1000/1300",
      "https://picsum.photos/seed/kid-002-2/1000/1300",
      "https://picsum.photos/seed/kid-002-3/1000/1300",
    ],
    category: "kids-wear",
    subcategory: "girls-ethnic",
    fabric: "Georgette",
    color: "Peacock Blue",
    size: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    stock: 51,
    sku: "KID-002",
    tags: ["girls-ethnic", "kids-wear", "peacock-blue"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 40,
  },
  {
    name: "Kids Cotton Kurta Pyjama - White",
    description:
      "Simple and comfortable white cotton kurta pyjama set for boys, ideal for everyday festive wear.",
    price: 899,
    originalPrice: 1099,
    images: [
      "https://picsum.photos/seed/kid-003-1/1000/1300",
      "https://picsum.photos/seed/kid-003-2/1000/1300",
      "https://picsum.photos/seed/kid-003-3/1000/1300",
    ],
    category: "kids-wear",
    subcategory: "boys-ethnic",
    fabric: "Cotton",
    color: "White",
    size: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    stock: 28,
    sku: "KID-003",
    tags: ["boys-ethnic", "kids-wear", "white"],
    isActive: true,
    isFeatured: false,
    rating: 4.3,
    reviewCount: 55,
  },
  {
    name: "Girls Anarkali Suit - Yellow",
    description:
      "Cheerful yellow Anarkali suit set for girls with fine embroidery and matching leggings.",
    price: 1499,
    originalPrice: 1899,
    images: [
      "https://picsum.photos/seed/kid-004-1/1000/1300",
      "https://picsum.photos/seed/kid-004-2/1000/1300",
      "https://picsum.photos/seed/kid-004-3/1000/1300",
    ],
    category: "kids-wear",
    subcategory: "girls-ethnic",
    fabric: "Georgette",
    color: "Yellow",
    size: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    stock: 27,
    sku: "KID-004",
    tags: ["girls-ethnic", "kids-wear", "yellow"],
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 54,
  },
  {
    name: "Kids Nehru Jacket Set - Navy Gold",
    description:
      "Festive navy and gold Nehru jacket set with kurta and pyjama for boys, great for weddings.",
    price: 1999,
    originalPrice: 2399,
    images: [
      "https://picsum.photos/seed/kid-005-1/1000/1300",
      "https://picsum.photos/seed/kid-005-2/1000/1300",
      "https://picsum.photos/seed/kid-005-3/1000/1300",
    ],
    category: "kids-wear",
    subcategory: "boys-ethnic",
    fabric: "Brocade",
    color: "Navy & Gold",
    size: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    stock: 24,
    sku: "KID-005",
    tags: ["boys-ethnic", "kids-wear", "navy-&-gold"],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 38,
  },
  {
    name: "Girls Cotton Frock - Floral Print",
    description:
      "Everyday cotton floral print frock for girls with puff sleeves and comfortable elastic waist.",
    price: 699,
    originalPrice: 899,
    images: [
      "https://picsum.photos/seed/kid-006-1/1000/1300",
      "https://picsum.photos/seed/kid-006-2/1000/1300",
      "https://picsum.photos/seed/kid-006-3/1000/1300",
    ],
    category: "kids-wear",
    subcategory: "girls-casual",
    fabric: "Cotton",
    color: "Floral Print",
    size: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    stock: 20,
    sku: "KID-006",
    tags: ["girls-casual", "kids-wear", "floral-print"],
    isActive: true,
    isFeatured: false,
    rating: 4.8,
    reviewCount: 56,
  },
  {
    name: "Kids Dhoti Set - Pastel Blue",
    description:
      "Soft pastel blue dhoti kurta set for toddlers, gentle on skin with breathable cotton fabric.",
    price: 999,
    originalPrice: 1249,
    images: [
      "https://picsum.photos/seed/kid-007-1/1000/1300",
      "https://picsum.photos/seed/kid-007-2/1000/1300",
      "https://picsum.photos/seed/kid-007-3/1000/1300",
    ],
    category: "kids-wear",
    subcategory: "boys-ethnic",
    fabric: "Cotton",
    color: "Pastel Blue",
    size: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    stock: 44,
    sku: "KID-007",
    tags: ["boys-ethnic", "kids-wear", "pastel-blue"],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 41,
  },
];

async function seed() {
  const shouldClear = process.argv.includes("--clear") || true; // Always clear when seeding new schema

  try {
    console.log("🔌 Connecting to database...");
    await connectDB();

    if (shouldClear) {
      console.log("🗑️  Clearing existing products collection...");
      await Product.deleteMany({});
      console.log("✅ Existing products collection cleared");
    }

    console.log(`🌱 Seeding ${products.length} products according to the updated Product model...`);
    const inserted = await Product.insertMany(products);

    const featuredCount = inserted.filter((p) => p.isFeatured).length;
    const categories = [...new Set(inserted.map((p) => p.category))];

    console.log("\n✅ Seed completed successfully!");
    console.log(`📦 Total products inserted: ${inserted.length}`);
    console.log(`⭐ Featured products: ${featuredCount}`);
    console.log(`📂 Categories: ${categories.join(", ")}`);
    console.log("\n📋 Products summary:");
    inserted.forEach((p, i) => {
      const sale = p.originalPrice ? ` (was ₹${p.originalPrice})` : "";
      console.log(
        `  ${i + 1}. [${p.sku}] ${p.name} - ₹${p.price}${sale} [${p.category}] ${p.isFeatured ? "⭐" : ""
        }`
      );
    });
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  } finally {
    await mongoose.connection.close();
    console.log("\n🔌 Database connection closed");
    process.exit(0);
  }
}

seed();